name: Build Site

on:
  push:
    branches:
      - "*"
    paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.mjs"
      - "**/bun.lockb"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-site-test:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Site
        run: bun run build
